name: movie_db
description: this app created with clean arch bloc

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio:
  equatable:
  flutter_screenutil:
  flutter_svg:
  flutter_rating_bar: ^4.0.1
  flutter_modular:
  http:
  mvc_pattern:
  path_provider:
  shared_preferences:
  intl:
  shimmer:
  google_fonts:
  provider:
  cached_network_image:
  animate_do:
  flutter_bloc:
  fluttertoast:
  dartz:
  carousel_slider:
  image_picker:
  get_it:
  awesome_dialog:
  flutter_staggered_grid_view:
  transparent_image:
  lottie: ^2.5.0
  percent_indicator: ^4.2.3
  firebase_auth: ^4.7.2
  firebase_core:
  cupertino_icons: ^1.0.2
  google_sign_in:
  flutter_launcher_icons:
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/splashImage.png"



flutter:


  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg




  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
